/**
 * Seed exercise_environments with sandbox configurations for each supported language.
 *
 * Run via: npx tsx scripts/seed-environments.ts
 *
 * Update the FLY_SANDBOX_APP value to match your Fly app name after deployment.
 * For local development, the base_image values won't be used directly — the
 * test-sandboxes.sh script uses local Docker images instead.
 */

// ============================================================
// CONFIGURATION — update these after deploying sandbox images
// ============================================================
const FLY_SANDBOX_APP = process.env.FLY_SANDBOX_APP || 'codeforge-sandboxes';
const REGISTRY = 'registry.fly.io';

// ============================================================
// Environment definitions
// ============================================================

interface EnvironmentSeed {
  name: string;
  display_name: string;
  description: string;
  base_image: string;
  preinstalled_packages: string[];
  setup_commands: string[];
  supported_languages: string[];
  max_execution_seconds: number;
  max_files: number;
  max_file_size_bytes: number;
  metadata: Record<string, unknown>;
}

const environments: EnvironmentSeed[] = [
  {
    name: 'python-3.12',
    display_name: 'Python 3.12',
    description:
      'Python 3.12 with pytest for testing. Suitable for algorithm, data structure, and general Python exercises.',
    base_image: `${REGISTRY}/${FLY_SANDBOX_APP}:sandbox-python`,
    preinstalled_packages: ['pytest', 'pytest-json-report', 'pytest-timeout'],
    setup_commands: [],
    supported_languages: ['python'],
    max_execution_seconds: 30,
    max_files: 20,
    max_file_size_bytes: 1_048_576, // 1MB
    metadata: {
      runtime_version: '3.12',
      test_framework: 'pytest',
      file_extension: '.py',
    },
  },
  {
    name: 'javascript-node20',
    display_name: 'JavaScript (Node.js 20)',
    description:
      'Node.js 20 with Vitest for testing. Suitable for JavaScript algorithm, DOM-free, and Node.js exercises.',
    base_image: `${REGISTRY}/${FLY_SANDBOX_APP}:sandbox-javascript`,
    preinstalled_packages: ['vitest'],
    setup_commands: [],
    supported_languages: ['javascript'],
    max_execution_seconds: 30,
    max_files: 20,
    max_file_size_bytes: 1_048_576,
    metadata: {
      runtime_version: '20',
      test_framework: 'vitest',
      file_extension: '.mjs',
    },
  },
  {
    name: 'typescript-node20',
    display_name: 'TypeScript (Node.js 20)',
    description:
      'Node.js 20 with tsx and Vitest for testing. Runs TypeScript directly without a separate compile step.',
    base_image: `${REGISTRY}/${FLY_SANDBOX_APP}:sandbox-typescript`,
    preinstalled_packages: ['vitest', 'tsx'],
    setup_commands: [],
    supported_languages: ['typescript'],
    max_execution_seconds: 30,
    max_files: 20,
    max_file_size_bytes: 1_048_576,
    metadata: {
      runtime_version: '20',
      test_framework: 'vitest',
      file_extension: '.ts',
    },
  },
];

// ============================================================
// SQL output (can be piped to psql or used with Drizzle)
// ============================================================

function generateSQL(): string {
  const statements = environments.map((env) => {
    return `INSERT INTO exercise_environments (
  name, display_name, description, base_image,
  preinstalled_packages, setup_commands, supported_languages,
  max_execution_seconds, max_files, max_file_size_bytes, metadata
) VALUES (
  '${env.name}',
  '${env.display_name}',
  '${env.description}',
  '${env.base_image}',
  '${JSON.stringify(env.preinstalled_packages)}'::jsonb,
  ARRAY[${env.setup_commands.map((c) => `'${c}'`).join(', ')}]::text[],
  ARRAY[${env.supported_languages.map((l) => `'${l}'`).join(', ')}]::text[],
  ${env.max_execution_seconds},
  ${env.max_files},
  ${env.max_file_size_bytes},
  '${JSON.stringify(env.metadata)}'::jsonb
) ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  base_image = EXCLUDED.base_image,
  preinstalled_packages = EXCLUDED.preinstalled_packages,
  setup_commands = EXCLUDED.setup_commands,
  supported_languages = EXCLUDED.supported_languages,
  max_execution_seconds = EXCLUDED.max_execution_seconds,
  max_files = EXCLUDED.max_files,
  max_file_size_bytes = EXCLUDED.max_file_size_bytes,
  metadata = EXCLUDED.metadata,
  updated_at = now();`;
  });

  return statements.join('\n\n');
}

console.log('-- CodeForge: Seed exercise_environments');
console.log('-- Generated by scripts/seed-environments.ts');
console.log('');
console.log(generateSQL());
